{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "will-it-compile.fullname" . }}
  labels:
    {{- include "will-it-compile.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "will-it-compile.selectorLabels" . | nindent 6 }}
{{- end }}
