{{- if and .Values.redis.enabled .Values.redis.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "will-it-compile.fullname" . }}-redis-secret
  labels:
    {{- include "will-it-compile.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  {{- if .Values.redis.auth.password }}
  password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
